resend.api-key=${RESEND_API_KEY}
resend.mail=${RESEND_MAIL}
resend.association-email-contact=${RESEND_ASSOCIATION_EMAIL_CONTACT}
resend.association-email-museum=${RESEND_ASSOCIATION_EMAIL_MUSEUM}
resend.association-email-museum-2=${RESEND_ASSOCIATION_EMAIL_MUSEUM_2}
resend.association-email-inscription=${RESEND_ASSOCIATION_EMAIL_INSCRIPTION}
